Task_1_1_1
vhlebnikov/OOP pull request #12
Opened 2022-09-23 18:06 UTC by vhlebnikov

2022-09-25 15:17 UTC, shadrina requested changes

2022-09-25 15:17 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/khlebnikov/MyTest.java
> +public class MyTest {
Обычно называют `HeapSortTest`: по имени класса, который тестируется

2022-09-25 15:17 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/khlebnikov/MyTest.java
> +    int[] ans;
Это лишнее. Скорее запутывает, чем приносит какую-то пользу

2022-09-25 15:17 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/khlebnikov/MyTest.java
> +    public void secondTest() {
Называйте, пожалуйста, любые программные сущности осмысленными именами. Номер смысловой нагрузки не несет. `testRegularArray`, `testEmptyArray` и так далее

2022-09-25 15:17 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/khlebnikov/MyTest.java
> +    // test with reversed array
Можно было эту информацию засунуть в названии метода и убрать комментарий

2022-09-25 15:17 UTC, shadrina commented on Task_1_1_1/script.bat
> +jar cf .\make\jar\HeapSort.jar -C .\make\bin .
Нет исполнения. Команда `java`

2022-09-25 17:57 UTC, vhlebnikov commented
Исправил ошибки.

2022-09-28 05:12 UTC, shadrina approved these changes
Сдано

2022-09-28 05:12 UTC, shadrina commented on Task_1_1_1/.gitignore
> +.gradle/
Почему вы не пользуетесь сгенеренным gitignore? Уже у четвертого человека вижу эту копипасту

2022-09-28 06:46 UTC, merged