Task_1_2_1
vhlebnikov/OOP pull request #13
Opened 2022-09-27 16:42 UTC by vhlebnikov

2022-10-02 09:29 UTC, vhlebnikov commented
@shadrina ответьте пожалуйста нормально или нет

2022-10-03 11:04 UTC, shadrina requested changes
В целом код хороший

2022-10-03 11:04 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/khlebnikov/Stack.java
> +        capacity *= 2;
На почитать: https://stackoverflow.com/questions/1100311/what-is-the-ideal-growth-rate-for-a-dynamically-allocated-array

2022-10-03 11:04 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/khlebnikov/Stack.java
> +    private void realloc() {
Соблюдаем какую-то логику в размещении методов. Я обычно приватные (которые касаются внутренностей) опускаю вниз класса. Кто-то делает наоборот. Выбери понравившийся вариант.

2022-10-03 11:04 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/khlebnikov/Stack.java
> +    public Stack<T> popStack(int count) {
С логикой тут все хорошо, но много повторяющегося кода в блоках if и else. Погугли, пожалуйста, как работает "элвис-оператор": `condition ? expression1 : expression2` и перепиши красиво.

2022-10-03 11:04 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/khlebnikov/Stack.java
> +    }
Убираем вот это и переопределяем equals и hashCode

2022-10-05 06:51 UTC, shadrina reviewed
Обсудили

2022-10-05 08:52 UTC, shadrina approved these changes
Сдано

2022-10-05 08:52 UTC, shadrina commented on Task_1_2_1/settings.gradle
> +include 'src'
Следите вот за этим, такого не должно быть

2022-10-05 16:03 UTC, merged