Task_1_2_2
vhlebnikov/OOP pull request #15
Opened 2022-10-25 23:41 UTC by vhlebnikov

2022-10-31 14:04 UTC, shadrina requested changes
Какой процент кода написан самостоятельно?

2022-10-31 14:04 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/BreathFirstSearch.java
> +import java.util.Queue;
Используем более новый `java.util.Deque`.

2022-10-31 14:04 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/BreathFirstSearch.java
> +public class BreathFirstSearch<T> implements Iterator<T> {
Раз это в первую очередь итератор, его лучше итератором и назвать: `BreathFirstSearchIterator`

2022-10-31 14:04 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +    private int typeOfSearch;
Такое проворачивается с помощью `enum`'ов

2022-10-31 14:04 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +    public Tree<T> addChild(T data) {
В условии задачи (пример) два разных метода add. У тебя вижу только один

2022-10-31 17:54 UTC, vhlebnikov commented
В коде подсмотрел только, как нужно реализовывать iterator.
А зачем мне добавлять метод вида tree.add(nodeB, "AB")? Я так понимаю tree тут это корень дерева, требуется добавить к вершине NodeB потомка со значением "AB". Всё то же самое можно сделать мои методом addChild (nodeB.addChild("AB").
Отличие только в том, что в первом методе мне изначально будет известен корень, в отличие от второго метода, где я получаю его через getRoot.

2022-11-07 10:36 UTC, shadrina requested changes

2022-11-07 10:36 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +public class Tree<T> extends ArrayList<T> implements Iterable<T> {
```
extends ArrayList<T>
```

Вот это интересно, объясни, пожалуйста, для чего так

2022-11-07 10:36 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +    private ArrayList<Tree<T>> children;
Используются ли какие-то методы непосредственно ArrayList'а? Или достаточно List?

2022-11-07 10:36 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +    public boolean treeEquals(Tree<T> tree) throws Exception {
Зачем этот метод, если есть equals?

2022-11-07 10:36 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +            ArrayList<Tree<T>> subList =
Аналогично про разницу ArrayList/List

2022-11-07 10:36 UTC, shadrina commented on Task_1_2_2/src/test/java/ru/nsu/khlebnikov/TreeTest.java
> +        Tree<Integer> root = new Tree<>(1);
Если тестируете дженерик, постарайтесь аргумент варьировать, а то тесты только с Integer

2022-11-07 10:50 UTC, vhlebnikov commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +public class Tree<T> extends ArrayList<T> implements Iterable<T> {
Тут ошибка, IDE случайно подставила наверное

2022-11-07 10:53 UTC, vhlebnikov commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +    private ArrayList<Tree<T>> children;
Извините не понял ваш вопрос, ArrayList это же реализация List, я же не могу просто так List использовать, может вы имели ввиду LinkedList, но он мне тут не подходит (ответ в следующем комментарии)

2022-11-07 10:55 UTC, vhlebnikov commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +    public boolean treeEquals(Tree<T> tree) throws Exception {
Equals сравнивает отдельные вершины, а  TreeEquals сравнивает деревья целиком

2022-11-07 11:02 UTC, vhlebnikov commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +            ArrayList<Tree<T>> subList =
Как я понимаю, метод subList копирует последовательный участок памяти в массиве, так как элементы в памяти расположены друг за другом, в отличие от LinkedList, где элементы расположены где-то в куче

2022-11-09 05:56 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/khlebnikov/Tree.java
> +            ArrayList<Tree<T>> subList =
Подойдешь, я этот момент немного тебе разжую

2022-11-09 05:57 UTC, shadrina reviewed
Обсудим очно

2022-11-09 07:09 UTC, vhlebnikov commented
Можно merge'ить?

2022-11-10 16:28 UTC, shadrina approved these changes
В остальном ок

2022-11-10 16:28 UTC, shadrina commented on Task_1_2_2/src/test/java/ru/nsu/khlebnikov/TreeTest.java
> +        ArrayList<Integer> actual = new ArrayList<>();
Ну вот когда вот такое поправишь по всему файлу, тогда можно..

2022-11-10 17:47 UTC, merged