Task_1_3_1
vhlebnikov/OOP pull request #18
Opened 2022-11-16 23:01 UTC by vhlebnikov

2022-11-24 18:40 UTC, vhlebnikov commented
@shadrina посмотрите пожалуйста, хотелось бы сдать это ещё до hard дедлайна

2022-11-29 12:14 UTC, shadrina requested changes
Сколько на твоей машине исполняется большой тест?

2022-11-29 12:14 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/khlebnikov/FileCreator.java
> +            }
У тебя в сигнатуре прописано `throws IOException`, это можно убрать.

2022-11-29 12:14 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/khlebnikov/FileCreator.java
> +        File file = new File("src/test/resources/", fileName);
Создавать тестовый файл можно где угодно, необязательно в ресурсах. Тем более что в конце этот файл должен удаляться. А он удаляется кстати?

2022-11-29 12:14 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/khlebnikov/FileCreator.java
> +    public static void createFile(String fileName) throws IOException, IllegalArgumentException {
Вопрос на сдачу: чем отличаются проверяемые исключения от непроверяемых? И почему `IllegalArgumentException` тут можно не указывать?

2022-11-29 12:14 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/khlebnikov/FileCreator.java
> +        if (!file.exists()) {
Было бы симпатичнее написать 
```
if (file.exists()) {
    throw ...
}
// И далее сразу try без лишней вложенности
try (PrintWriter pw = new PrintWriter(file)) {
    // ... 
}
```

2022-11-29 12:14 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/khlebnikov/SubStringFinder.java
> +     *              to rewrite the code by adding 1 to the elements of the answer)
У тебя тут используется пара. В стандартной библиотеке пары, к сожалению, нет, но тебе ничего не мешает сделать свой класс `Pair` так, как удобно.

2022-11-29 12:14 UTC, shadrina commented on Task_1_3_1/src/test/java/ru/nsu/khlebnikov/SubStringFinderTest.java
> +                        Arrays.asList(2, 5));
И у своего класса `Pair` сделать такой же красивый статический инициализатор `Pair.create(1,2)`

2022-11-29 12:14 UTC, shadrina commented on Task_1_3_1/src/test/java/ru/nsu/khlebnikov/SubStringFinderTest.java
> +                        Arrays.asList(2, 5));
Ну чтобы не плодить `new Pair` везде

2022-11-29 12:17 UTC, shadrina commented
Ну и самая большая проблема в том, что этот PR удаляет содержимое двух предыдущих, посмотри вкладку Files changed

2022-11-29 14:47 UTC, vhlebnikov commented on Task_1_3_1/src/main/java/ru/nsu/khlebnikov/FileCreator.java
> +    public static void createFile(String fileName) throws IOException, IllegalArgumentException {
Проверяемые исключения проверяются во время компиляции программы, их нужно обрабатывать вручную

> Сколько на твоей машине исполняется большой тест?

За 4 минуты 55 секунд
![image](https://user-images.githubusercontent.com/91516875/204560421-cba2d066-109b-43cf-9495-fc6f58fd9c16.png)

2022-11-29 14:50 UTC, vhlebnikov commented
> Ну и самая большая проблема в том, что этот PR удаляет содержимое двух предыдущих, посмотри вкладку Files changed

Насколько я помню, у меня была проблема, что CI не хотел работать, и я решил заново открыть PR. наверное из-за этого предыдущие PR здесь не видно.

2022-11-29 14:51 UTC, vhlebnikov commented
> Сколько на твоей машине исполняется большой тест?

За 4 минуты 55 секунды
![image](https://user-images.githubusercontent.com/91516875/204561426-7293d620-8e78-4f36-a1d2-55be86b18044.png)

2022-11-29 14:58 UTC, vhlebnikov commented on Task_1_3_1/src/main/java/ru/nsu/khlebnikov/FileCreator.java
> +        File file = new File("src/test/resources/", fileName);
Сейчас сделаю удаление, создание файла в ресурсах сделал для удобства или лучше сделать, чтобы нужно было указывать полный путь?

2022-11-29 19:16 UTC, vhlebnikov commented on Task_1_3_1/src/main/java/ru/nsu/khlebnikov/FileCreator.java
> +    public static void createFile(String fileName) throws IOException, IllegalArgumentException {
Проверяемые исключения проверяются во время компиляции, их нужно либо обработать, либо пробросить наверх. (либо в блоке catch, либо throws в сигнатуре метода)
Непроверяемые исключения не проверяются во время компиляции (то есть если даже в ходе исполнения программы непроверяемое исключение будет кинуто, компилятор от этого не предостережёт), их не нужно обрабатывать вручную, возникают во время исполнения программы, являются наследниками RuntimeExceprion (или им самим).

Так как IllegalArgumentException является непроверяемым исключением, мне о нём заботиться не надо, в итоге заменил его на FileAlreadyExistsException, которое является проверяемым (т.к. наследник IOException), так как хочу, чтобы я всё же точно указывал, что произошло.

2022-11-29 19:26 UTC, vhlebnikov commented
Добавил удаление файла, теперь проходит за 5 минут 4 секунды

![image](https://user-images.githubusercontent.com/91516875/204628971-f5e21c32-d366-4e37-b155-326cb28d8004.png)

2022-11-30 07:13 UTC, vhlebnikov commented
Заметки:

- Сделать у Pair другой параметр

- Проверить работу с JAR (скрипт с первой лабы)

2022-11-30 18:48 UTC, vhlebnikov commented
Насчёт JAR, у меня не получилось его создать, я смог сделать бинарники классов, которые в папке main лежат, а с test у меня произошла ошибка:
![image](https://user-images.githubusercontent.com/91516875/204881382-fe13132b-99b2-44eb-9203-5d447f67bb28.png)
Как я только не пробовал эту библиотеку указывать в sourcepath, ничего не вышло.
Непонятно, как в итоге мне скомпилировать класс для тестов, поэтому, так как пока что заменю указание названия файла на указание абсолютного пути к нему в методах, где это нужно.

2022-12-01 18:16 UTC, vhlebnikov commented
У меня наконец-то получилось создать JAR  файл и исполнить его. Я не стал компилировать класс с тестами, так как javac говорил, что пакета org.junit.jupiter.api не существует, я пробовал явно указать к нему путь, но он всё равно ругался. По этой причине я создал отдельный класс с main, куда перенёс первый тест и вывел ответ в консоль.

TestForJAR.java
`package ru.nsu.khlebnikov;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.List;

public class TestForJAR {
    public static void main(String[] args) throws IOException {
        List<Pair<Integer>> expected = List.of(Pair.create(0, 7));
        List<Pair<Integer>> actual = SubStringFinder.findSubString("input_rus.txt", "пирог");
        System.out.println(actual.equals(expected));
        Reader file = new FileReader("src/test/resources/input_rus.txt",
                StandardCharsets.UTF_8);
        Reader reader = new BufferedReader(file);
        int r;
        while ((r = reader.read()) != -1) {
            System.out.print((char) r);
        }
        System.out.println();
        System.out.println(TestForJAR.class.getProtectionDomain().getCodeSource().getLocation().getPath());
    }
}
`
script.bat
`javac -d .\make\bin\ .\src\main\java\ru\nsu\khlebnikov\*

javac -d .\make\bin\ -sourcepath .\src\main\java .\src\test\java\ru\nsu\khlebnikov\TestForJAR.java

mkdir .\make\jar
jar cf .\make\jar\SubStringFinder.jar -C .\make\bin .

java -classpath .\make\jar\SubStringFinder.jar ru.nsu.khlebnikov.TestForJAR`

В итоге ещё пришлось JDK обновить на 19 версию, компилятор сам меня об этом попросил, в итоге всё работает.
Попробовал переместить jar в другое место файловой системы, создал папку где лежит jar и папка вида src\test\resources\(текстовые файлы для тестов). Всё запустилось, всё работает.

2022-12-08 11:21 UTC, shadrina requested changes
1. Не поленилась, склонировала проект, собрала JAR, исполнила в директории, отличной от корня проекта. Вот что вышло:

```
% java -classpath Task_1_3_1-1.0-SNAPSHOT.jar ru.nsu.khlebnikov.Main 
Exception in thread "main" java.io.FileNotFoundException: File doesn't exist
	at ru.nsu.khlebnikov.SubStringFinder.findSubString(SubStringFinder.java:77)
	at ru.nsu.khlebnikov.Main.main(Main.java:13)
```
И это ожидаемое поведение, так как относительный путь `src/test/resources/...` на то и относительный, что задает файл относительно директории, в которой JAR исполняется. Я к чему все это вела: читать из ресурсов надо с помощью `getResourceAsStream()`. Сама-то папка resources дублируется в JAR'е, но до нее нужно правильно доступаться. Именно для этого существует этот метод (их таких несколько, посмотри в интернете).

И еще на будущее. JAR собирать можно попроще, это умеет делать Gradle с помощью команды `jar`.

2. Надо вернуть на место предыдущие задачи, которые в этом PR удаляются. Посмотри вкладку Files changed.

2022-12-15 02:46 UTC, vhlebnikov commented
@shadrina

Используя getResourceAsStream, который кидает NullPointerException, хотелось бы его обработать, в том смысле, что просто кинуть исключение с сообщением, что файл не найден, но ведь я не должен обрабатывать непроверяемые исключения.
Нашёл на stackoverflow [тему](https://stackoverflow.com/questions/29194380/checked-and-unchecked-exception-in-java-are-these-assertions-true), где это обсуждается, говорят, что для непроверяемого исключения всё же можно кинуть ошибку, тем более, что мой класс является "at the very top level" моей программы. 

Собственно вопрос: могу ли я "обработать" NullPointerException таким образом?

2022-12-15 12:29 UTC, vhlebnikov commented
Весь день бьюсь над проблемой: метод, который создаёт файл, не создаёт его сразу, а только по завершении программы. То есть мне надо создать файл, найти в нём подстроку, потом его удалить. При первом запуске он кидает исключение, что файл не найден, когда пытается найти подстроку, при втором запуске при попытке создать файл кидает исключение, что файл уже существует.

Вот такая вот беда.

2022-12-15 13:59 UTC, vhlebnikov commented
Всё определённо ломает getResources, не может найти файл, хотя он создался на диске, если искать файлы по относительному пути, всё работает

2022-12-15 14:03 UTC, vhlebnikov commented
Проблема [ясна](https://stackoverflow.com/questions/33584768/how-to-refresh-src-main-resources-folder-while-executing-the-code)

2022-12-15 14:31 UTC, vhlebnikov commented
Сделал два отдельных метода для файлов из ресурсов и для различных путей, надеюсь это считается за решение проблемы. (можно бы было конечно скопировать файл в папку build/..., но как-то это глупо).

2022-12-20 11:07 UTC, shadrina approved these changes
1. Обрабатывать NPE и другие рантайм исключения можно и нужно, если того требует задача. Они называются непроверяемыми, потому что их просто **можно** не проверять.
2. Есть файлы, которые изначально поставляются с твоей программой, в том числе тесты. Они лежат в папке ресурсов, эта папка копируется в JAR. Для их чтения мы используем getResourceAsStream.
3. Есть файлы, которые ты создаешь во время работы программы. Их можно создавать где угодно относительно того места, где исполняется JAR. Для чтения созданного тобою только что файла не надо использовать getResourceAsStream. Можно читать обычным способом.

2022-12-20 11:09 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/khlebnikov/SubStringFinder.java
> +             BufferedInputStream reader = new BufferedInputStream(fileInputStream)
Вот только опять и снова напомню, что слева мы пишем интерфейс

2022-12-20 11:49 UTC, merged