Task_1_4_1
vhlebnikov/OOP pull request #19
Opened 2022-11-23 13:55 UTC by vhlebnikov

2022-11-24 17:41 UTC, vhlebnikov commented
Выяснил, что CI по умолчанию запускает код с JDK 11, нашёл способ как заставить его работать с JDK 17.
![image](https://user-images.githubusercontent.com/91516875/203841993-64ae9c07-d894-48fe-ae65-043d0ccb73b1.png)

2022-11-24 17:44 UTC, vhlebnikov commented
Не могу разобраться как в нгушной зачётке высчитывается средний бал (изначально путём решения простых уравнений выяснил, что зачёт == 4, но потом понял насколько это глупо, глупо когда получаешь зачёт, а средний бал только ухудшается 🤔). Поставил для зачёта значение 5 (вроде логично), но средний бал не совпадает с тем, который в моей зачётной книжке.

2022-11-24 18:39 UTC, vhlebnikov commented
@shadrina не стал вас добавлять в reviewer'ы на софт дедлайн, чтобы не замучить вас миллионами своих комитов из-за разбирательств с CI.

2022-11-29 13:23 UTC, shadrina commented
Мне кажется, зачеты просто не считаются

2022-11-29 13:51 UTC, shadrina requested changes
1. Снова удаляется код предыдущих лаб
2. В целом не очень читаемо, но это лечится разбивкой на методы и грамотным использованием Stream API.
3. Правок хоть и много, но они все полезные. Видно, что придумывал и писал все сам, это путь к успеху 👍

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/Subject.java
> +public class Subject {
Это можно сделать `record`

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +        try (FileReader file = new FileReader("src/test/resources/" + fileName,
Проверь, пожалуйста, будет ли этот метод работать, если разместить JAR в рандомном месте файловой системы

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +        try (FileReader file = new FileReader("src/test/resources/" + fileName,
Тут кстати тот же прикол, что и с List/ArrayList. Есть интерфейс Reader

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +                }
Давай использовать регулярные выражения. Код уменьшится в несколько раз и станет читаем.

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +                    switch (subject.getMark()) {
1. `switch` в `if`, который в `for`, который в `for`. Как раз случай, когда нужно использовать Stream API. Тебе понадобится какой-нибудь `values()`, `flatMap()`, `map()` и `reduce()`. Начальная точка `subjects`.
2. Строки не нужно оборачивать в скобки
3. Давай для оценок сделаем отдельный enum

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +                switch (subject.getMark()) {
Аналогично тут просится Stream API

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +            return "да";
Может, просто boolean?

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +            return "недостаточно информации";
В этом случае можно кидать exception

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +                        && !subject.getMark().equals("Зачёт")) {
Вот такую многословность вылечит enum для оценок

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +                return "недостаточно информации";
В исключительных ситуациях надо кидать исключения

2022-11-29 13:51 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +                        + " семестр: " + increasedScholarship(Integer.toString(i)));
Давай вот эту логику отразим в переопределенном `toString()`, а в этом методе просто результирующую строку запишем в файл.

2022-12-16 07:16 UTC, vhlebnikov commented on Task_1_4_1/src/main/java/ru/nsu/khlebnikov/GradeBook.java
> +        try (FileReader file = new FileReader("src/test/resources/" + fileName,
Если писать так Reader reader = new BufferedReader(file), то он не сможет найти метод readLine, так как его реализовывает класс BufferedReader, который расширяет Reader.

2022-12-21 14:24 UTC, closed without merging